# Generated by Django 3.0.5 on 2020-04-27 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usercontent', '0002_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='usercontent.Blog'),
        ),
        migrations.AlterField(
            model_name='like',
            name='podcast',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='usercontent.Podcast'),
        ),
        migrations.AlterField(
            model_name='like',
            name='youtube',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='usercontent.Youtube'),
        ),
    ]
