# Generated by Django 3.0.5 on 2020-04-30 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usercontent', '0003_auto_20200430_1658'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Like',
        ),
    ]
