# Generated by Django 3.0.5 on 2020-04-24 18:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('usercontent', '0003_auto_20200423_1812'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YoutubeChannel',
            new_name='Youtube',
        ),
    ]
