# Generated by Django 3.0.5 on 2020-04-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercontent', '0004_auto_20200427_1142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='podcast',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='podcast',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='youtube',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='youtube',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='like',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='like',
            name='podcast',
        ),
        migrations.RemoveField(
            model_name='like',
            name='youtube',
        ),
        migrations.AlterField(
            model_name='post',
            name='content_type',
            field=models.CharField(choices=[('Blog', 'Blog'), ('Podcast', 'Podcast'), ('Youtube', 'Youtube'), ('Other', 'Other')], default='other', max_length=20),
        ),
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Podcast',
        ),
        migrations.DeleteModel(
            name='Youtube',
        ),
    ]
