# Generated by Django 3.0.5 on 2020-04-24 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercontent', '0004_auto_20200424_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='slug',
            field=models.CharField(default='blogs', max_length=20),
        ),
        migrations.AddField(
            model_name='podcast',
            name='slug',
            field=models.CharField(default='podcasts', max_length=20),
        ),
        migrations.AddField(
            model_name='youtube',
            name='slug',
            field=models.CharField(default='youtube', max_length=20),
        ),
    ]
