# Generated by Django 3.0.5 on 2020-05-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercontent', '0005_auto_20200430_2154'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
