# Generated by Django 3.0.5 on 2020-04-25 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercontent', '0005_auto_20200424_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='url',
            field=models.URLField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='podcast',
            name='url',
            field=models.URLField(max_length=250, unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='youtube',
            name='url',
            field=models.URLField(max_length=250, unique=True),
        ),
    ]
