# Generated by Django 3.0.5 on 2020-05-21 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercontent', '0007_auto_20200520_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content_type',
            field=models.CharField(choices=[('Blog', 'Blog'), ('Podcast', 'Podcast'), ('Youtube', 'Youtube'), ('Other', 'Other')], max_length=20),
        ),
    ]
