# Generated by Django 3.0.5 on 2020-04-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usercontent', '0005_auto_20200429_1519'),
        ('users', '0002_profile_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='liked',
            field=models.ManyToManyField(blank=True, to='usercontent.Post'),
        ),
    ]
